### ISSUE TITLE
Subject: installation

### ISSUE THREAD

**Issue by tboenig** [deutschestextarchiv/tocrify#12]
Hallo,
I'm installing tocrify. I have the feeling that something is missing. Because after ``pip install -r requirements.txt`` I get the error message: ``Could not open requirements file: [Errno 2] File or directory not found: 'requirements.txt'``. What is the problem? Thank's.

**Comment by wrznr** [comment]
Hello @tboenig,

many thanks for your interest in `tocrify`. As you can see in the code listing, `requirements.txt` is existing. From which directory are you running the `pip` command?
